# Generated by Django 5.0.3 on 2024-03-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesperson',
            table='Users',
        ),
    ]
